#spring.application.name=spring-ai-sample
spring:
  application:
    name: spring-ai-sample
  ai:
    ollama:
#      model: llama3
      chat:
        model: llama3.2
        options:
          temperature: 0
      #        model: deepseek-r1
      base-url: http://localhost:11434
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema-h2.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8888