CREATE TABLE IF NOT EXISTS SPRING_AI_CHAT_MEMORY (
    conversation_key VARCHAR(36) NOT NULL,
    content TEXT NOT NULL,
    type VARCHAR(10) NOT NULL CHECK (type IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL')),
    create_time TIMESTAMP NOT NULL
    );

CREATE INDEX IF NOT EXISTS SPRING_AI_CHAT_MEMORY_CONVERSATION_KEY_CREATE_TIME_IDX
    ON SPRING_AI_CHAT_MEMORY(conversation_key, create_time);

